# Stage 1: Build
# Using a specific version instead of 'latest' can help ensure reproducibility.
FROM node:16-alpine AS builder

# Set the working directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of your application code
COPY . .

# Prune development dependencies for production
RUN npm prune --production

# Stage 2: Runtime
FROM node:16-alpine

WORKDIR /usr/src/app

# Copy built node modules and other necessary files from the builder stage
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app ./

# Copy the entrypoint script into the container
COPY entrypoint.sh /usr/src/app/entrypoint.sh

# Ensure the entrypoint script is executable
RUN chmod +x /usr/src/app/entrypoint.sh

# Set the entrypoint to the script
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
